### ISSUE TITLE
Add a "developer mode"

### ISSUE THREAD

**Issue by azzlack** [VladimirRybalko/angular-applicationinsights#19]
Would be nice to have a flag you can set to true to make the service not post anything to AI but print it to the console instead

**Comment by khaines** [comment]
Thanks for the feedback. I can understand the use for this and it shouldn't be hard to implement.

**Comment by VladimirRybalko** [comment]
@khaines any news about 'developer mode'?
Seems that project was abandoned by the owner.

**Comment by khaines** [comment]
Yes, I'm not maintaining this codebase. If someone would like to own this project, I'm very willing to hand it over.

**Comment by ericmahlberg** [comment]
Would suggest using a different name - there is a property of the same name in the Insights assembly which has a very different impact: https://msdn.microsoft.com/en-us/library/microsoft.applicationinsights.channel.telemetrychannel.developermode.aspx

Also, it would be good if it were disabled by default - it took me a bit of digging to realize why my page view transitions weren't doing anything other than console logging (especially since the config options in the readme weren't updated to mention this)

**Comment by VladimirRybalko** [comment]
@khaines 
Your project is really interesting for me. Could you transfer me all required privileges?
I'm going to fix all existing issues and develop ability to supporting the angular2.
Thanks in advance.

**Comment by khaines** [comment]
@VladimirRybalko I certainly can transfer the main repository to you, however you need to remove your fork of the project or stash it somewhere. Github will say there is a naming collision if I try to transfer this code to you otherwise.

**Comment by VladimirRybalko** [comment]
@khaines there is no problem. I've done it. Please try again.

**Comment by khaines** [comment]
It's all yours, once you accept it. Thank you for taking the project on.

**Comment by VladimirRybalko** [comment]
@khaines thank you.
